/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-21 05:15:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.cj.x.protobuf.MysqlxPrepare.Execute;
import com.db.MyConnection;
import java.sql.*;

public final class editFood_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin/adminHeader.jsp", Long.valueOf(1663657085333L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.mysql.cj.x.protobuf.MysqlxPrepare.Execute");
    _jspx_imports_classes.add("com.db.MyConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/adminheader.css\">\r\n");
      out.write("<title>Admin Header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("	");
String email=session.getAttribute("username").toString(); 
      out.write("\r\n");
      out.write("		<div class=\"logo\"><span>Sand</span>wichhut</div>\r\n");
      out.write("		<div class=\"menu\">\r\n");
      out.write("			<a href=\"adminHome.jsp\">Home</a>\r\n");
      out.write("			<a href=\"addNewFood.jsp\">Add New Food </a>\r\n");
      out.write("			<a href=\"../SandServlet?act=getall\">All Food & Edit Foods</a>\r\n");
      out.write("			<a href=\"messageReceived.jsp\">Messages Received</a>\r\n");
      out.write("			<a href=\"orderReceived.jsp\">Orders Received</a>\r\n");
      out.write("			<a href=\"cancelOrders.jsp\">Cancel Orders</a>\r\n");
      out.write("			<a href=\"deliveredOrders.jsp\">Delivered Orders</a>\r\n");
      out.write("			<a href=\"../Logout.jsp\">Logout</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/addNewFood.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src='https://kit.fontawesome.com/a076d05399.js'></script>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Edit Food Details</title>	\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

int id=Integer.parseInt(request.getParameter("id"));
try{
	Connection conn=MyConnection.connect();
	Statement st=conn.createStatement();
	ResultSet rs=st.executeQuery("select * from food where foodid='"+id+"'");
	while(rs.next())
	{
		

      out.write("\r\n");
      out.write("<main class=\"regform\">\r\n");
      out.write("<section>\r\n");
      out.write("            <h1>Welcome</h1>\r\n");
      out.write("            <h4>Welcome,Please Enter Details to Update food</h4>\r\n");
      out.write("            <form  action=\"editFoodAction.jsp\" method=\"post\">\r\n");
      out.write("            \r\n");
      out.write("           		 <div class=\"field\">\r\n");
      out.write("                    \r\n");
      out.write("                    <input type=\"hidden\" name=\"foodid\" value=\"");
      out.print(rs.getInt(1) );
      out.write("\" class=\"input-field\"  required>\r\n");
      out.write("               	 </div>\r\n");
      out.write("               	 \r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"name\">Enter name of food</label>\r\n");
      out.write("                    <input type=\"text\" name=\"name\" value=\"");
      out.print(rs.getString(2) );
      out.write("\" class=\"input-field\"  required>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"category\">Enter category</label>\r\n");
      out.write("                    <input class=\"input-field\" type=\"text\" name=\"category\" value=\"");
      out.print(rs.getString(3) );
      out.write("\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"price\">Enter Price</label>\r\n");
      out.write("                    <input class=\"input-field\" type=\"text\" name=\"price\" value=\"");
      out.print(rs.getInt(4) );
      out.write("\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("               <div class=\"field\">\r\n");
      out.write("                    <label for=\"category\">Active</label>\r\n");
      out.write("                    <select class=\"input-field\" name=\"active\">\r\n");
      out.write("					   <option value=\"Yes\">Yes</option>\r\n");
      out.write("					   <option value=\"No\">No</option>\r\n");
      out.write("					</select>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"buttons\">\r\n");
      out.write("                 <input type=\"hidden\" name=\"act\" value=\"editFoodAction\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Save\" class=\"cta sign-in\">\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </form>\r\n");
      out.write("        </section>\r\n");
      out.write("      </main>\r\n");
      out.write("      \r\n");
      out.write("     ");

	} 
	}
catch(Exception e){
	System.out.println(e);
}
     
     
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
